### ISSUE TITLE
#fishackathon No code?

### ISSUE THREAD

**Issue by audreyt** [stwbt/fishfishfish#1]
請問簡報第三頁的程式是這次的作品嗎？如果是，程式碼是否有 `git add` 進來？

**Comment by stwbt** [comment]
你好
是
剛剛有重新上傳了

南臺灣大隊

2016-04-24 11:19 GMT+08:00 唐鳳 notifications@github.com:

**Comment by audreyt** [comment]
收到，是基於 DeepLearnToolbox 開發的吧？辛苦了，感謝
